### ISSUE TITLE
About Verdant 02 License

### ISSUE THREAD

**Issue by saoeee** [kreme123/Verdant02#1]
Hello Mr. Kreme, I am a student from China, my friends and I love your Verdant 02 very much and hope to get your authorization to support this non-profit project! We also hope that you can provide a hot swappable solution! If you can, I hope you can provide PCB schematic and PCB source files, thank you!！This is my email：qy735508@126.com  3243079485@qq.com

**Comment by kreme123** [comment]
Hi. Feel free to use these files for your project. I don't have plans to make hotswappable version. I will upload PCB and plate source files to github soon. You can use those files to modify hotswap version if needed.

**Comment by saoeee** [comment]
Can you tell me your email? I want to get in touch with you better！

**Comment by saoeee** [comment]
Can you tell me your email? I would like to get in touch with you better！！I have some keyboard knowledge that I would like to ask you about! Thank you!

**Comment by kreme123** [comment]
I sent you an email to qy735508@126.com

**Comment by saoeee** [comment]
I'm sorry, I mistyped this email, it should be qy7355608@126.com
